# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{varnish-rb}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrea Campi"]
  s.date = %q{2011-06-24}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{andrea.campi@zephirworks.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "VERSION",
    "lib/em/varnish/log_connection.rb",
    "lib/em/varnish/log_stream.rb",
    "lib/em/varnish/request_stream.rb",
    "lib/varnish.rb",
    "lib/varnish/connection.rb",
    "lib/varnish/log_entry.rb",
    "lib/varnish/vsl.rb",
    "lib/varnish/vsm.rb",
    "log.rb",
    "log_tailer.rb",
    "tailer.rb"
  ]
  s.homepage = %q{http://github.com/andreacampi/varnish-rb}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.1}
  s.summary = %q{TODO: one-line summary of your gem}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_runtime_dependency(%q<eventmachine>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_dependency(%q<eventmachine>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    s.add_dependency(%q<eventmachine>, [">= 0"])
  end
end

